# This file is part of REANA.
# Copyright (C) 2017, 2018 CERN.
#
# REANA is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# REANA is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with REANA; if not, see <http://www.gnu.org/licenses>.
#
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization or
# submit itself to any jurisdiction.

notifications:
  email: false

sudo: true

language: python

cache:
  - pip

python:
  - "3.6"

services:
  - docker

before_script:
- curl https://raw.githubusercontent.com/stoplightio/prism/master/install.sh | sudo sh
- prism run --mock --list --spec /home/travis/build/dinosk/reana-server/reana_server/openapi_connections/reana_workflow_controller.json &

before_install:
  - pip install -r requirements-dev.txt
  - travis_retry pip install --upgrade pip setuptools py
  - travis_retry pip install twine wheel coveralls

install:
  - travis_retry pip install -e .[all]

script:
  - ./run-tests.sh

after_success:
  - coveralls
